name: Run bgg-scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  

jobs:
  run_main_py:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run main.py
        env: 
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run: python main.py
